<a href="https://colab.research.google.com/github/VQuiMe/Ingenias_2025_DataScience/blob/main/Notebook_5_Entregable_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
import numpy as np

In [ ]:
# Crear un arreglo de ceros de longitud 12
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
arr = np.zeros(10)
arr[5] = 10
print(arr)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [ ]:
# Crear un arreglo que tenga los números del 10 al 49
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
arr = np.random.rand(100)
# print(arr)
print(f'Media: {arr.mean()} ; Varianza: {arr.var()}')

Media: 0.5014739327403861 ; Varianza: 0.08570188874709554


In [ ]:
# Calcular la media de un arreglo usando np.sum
# media = SUMA(arr) / (# elementos en arr)
arr = np.random.rand(5)
suma = arr.sum()
num = arr.size
print(arr)
print(f'Media: {suma / num}')

[0.84994788 0.6096222  0.87277726 0.73830719 0.12796128]
Media: 0.6397231631999105


In [ ]:
# Calcular la varianza de un arreglo usando np.sum y np.mean
# var = SUMA( (arr - media)^2 / (# elementos en arr) )
arr = np.random.rand(5)
media = np.mean(arr)
var = np.sum( (arr - media) ** 2 / arr.size)
# print(arr)
print(f'Varianza: {var}')

Varianza: 0.03576916712253453


In [ ]:
# Crear un array de números aleatorios usando np.random.randn.
np.random.randn(2, 3)

array([[ 1.10428901,  1.14512646, -0.33942881],
       [ 0.67214902, -0.29594202, -1.42887579]])